[project]
name = "liquid"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.water]
path = "contracts/water.clar"
depends_on = []
